steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/go-rest-api:latest', '.']
    dir: '.'  # Directory where your Dockerfile and Go application files are located
    waitFor: ['-']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', 'gcr.io/${_PROJECT_ID}/go-rest-api:latest']
    waitFor: ['Build']

  # Step 3: Set up the Kubernetes cluster context
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set Cluster Context'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER_NAME}'
      - '--zone'
      - '${_ZONE}'
    env:
      - 'CLOUDSDK_CORE_PROJECT=${_PROJECT_ID}'
    waitFor: ['Push']

  # Step 4: Deploy the application to Kubernetes using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy'
    args: ['apply', '-f', 'k8s/deployment.yaml']  # Path from the root directory
    waitFor: ['Set Cluster Context']

  # Step 5: Apply the Kubernetes service configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy Service'
    args: ['apply', '-f', 'k8s/service.yaml']  # Path from the root directory
    waitFor: ['Deploy']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY

# Define substitutions for dynamic values
substitutions:
  _PROJECT_ID: 'playground-s-11-5104e2ea'  # Replace with your GCP project ID
  _CLUSTER_NAME: 'my-go-rest-api-cluster'  # Replace with your cluster name
  _ZONE: 'us-central1-a'  # Replace with your cluster zone
